def decompress(decompress_bytes: bytes, uncompressed_size: int) -> bytes: ...
def decompress_buffer(
    decompress_bytes: bytes | bytearray | memoryview, uncompressed_size: int
) -> bytes: ...
def miki_decrypt(encrypted_bytes: bytes | bytearray | memoryview) -> bytes: ...
def miki_decrypt_old(encrypted_bytes: bytes | bytearray | memoryview) -> bytes: ...
def miki_decrypt_and_decompress(
    encrypted_bytes: bytes | bytearray | memoryview, uncompressed_size: int
) -> bytes: ...
def miki_decrypt_old_and_decompress(
    encrypted_bytes: bytes | bytearray | memoryview, uncompressed_size: int
) -> bytes: ...
